name: Test Site Dimitris
favicon: null
layout_spectrum: 0.7950713899917901
typography_spectrum: 0.10383607004769146
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#13171a'
    - '#757d87'
    - '#959fa9'
    - '#f3ffff'
    - '#b5c1cf'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
