name: Test Site Dimitris
favicon: null
layout_spectrum: 0.5737
typography_spectrum: 0.31155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#47473d'
    - '#e1caa0'
    - '#b79973'
    - '#fffffc'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
